#!/bin/bash
#$ -S /bin/bash
#$ -q short.q
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=80G
#$ -N combiner_demuxafy_TenK10K_scRNA
#$ -e /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/demuxafy_output/combined/logs/comb_TenK10K_scRNA_vireo_240115_no_cb.err
#$ -o /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/demuxafy_output/combined/logs/comb_TenK10K_scRNA_vireo_240115_no_cb.log
#$ -t 1-25
#$ -m ae
#$ -M a.cuomo@garvan.org.au

SIF=/share/ScratchGeneral/anncuo/software/Demuxafy.sif
BIND_PATH_DATA=/directflow
BIND_PATH_OUTPUT=/share/ScratchGeneral/anncuo

i=${SGE_TASK_ID};

SAMPLE=$(sed "${i}q;d" /share/ScratchGeneral/anncuo/tenk10k/data_processing/cellranger_outs_240115.txt)

echo "Combining all doublet detection results for sample: $SAMPLE"

OUTDIR="/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/demuxafy/combined_output_scds_scdblfinder_vireo_no_cb/$SAMPLE"
SCDS_OUTDIR="/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/demuxafy/scds_output/$SAMPLE"
SCDBLFINDER_OUTDIR="/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/demuxafy/scdblfinder_output/$SAMPLE"
VIREO_OUTDIR="/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/demuxafy/vireo_output_no_cb/$SAMPLE"

singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF Combine_Results.R \
                -o $OUTDIR/combined_results.tsv \
                --scds $SCDS_OUTDIR \
                --scDblFinder $SCDBLFINDER_OUTDIR \
                --vireo $VIREO_OUTDIR \
                --method "MajoritySinglet" ## there are other methods that can also be used, please see the help message above for the other options
