#!/bin/bash
#$ -S /bin/bash
#$ -q short.q
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=80G
#$ -N demuxalot_demuxafy_TenK10K_scRNA
#$ -e /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/demuxalot/logs/demuxalot_TenK10K_scRNA.err
#$ -o /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/demuxalot/logs/demuxalot_TenK10K_scRNA.log
#$ -t 1-64

SIF=/share/ScratchGeneral/anncuo/software/Demuxafy.sif
BIND_PATH_DATA=/directflow
BIND_PATH_OUTPUT=/share/ScratchGeneral/anncuo
​
i=${SGE_TASK_ID};

SAMPLE=$(sed "${i}q;d" /share/ScratchGeneral/anncuo/tenk10k/data_processing/cellranger_outs.txt)
​
echo "Performing Demuxalot demultiplexing + doublet detection on sample: $SAMPLE"
​
COUNTS="/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/$SAMPLE/outs/filtered_feature_bc_matrix.h5"
DEMUXALOT_OUTDIR="/share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/demuxalot_output/${SAMPLE}"

VCF=/path/to/TestData4PipelineFull/test_dataset.vcf
BARCODES=/path/to/TestData4PipelineFull/test_dataset/outs/filtered_gene_bc_matrices/Homo_sapiens_GRCh38p10/barcodes.tsv
BAM=/path/to/test_dataset/possorted_genome_bam.bam
DEMUXALOT_OUTDIR=/path/to/output/demuxalot
INDS=/path/to/TestData4PipelineFull/donor_list.txt

mkdir /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/demuxalot_output/${SAMPLE}
​
singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF python Demuxalot.py \
                -b $BARCODES \
                -a $BAM \
                -n $INDS \
                -v $VCF \
                -o $DEMUXALOT_OUTDIR \
                -r True


# Summarise results (with and without refinement)
singularity exec Demuxafy.sif bash Demuxalot_summary.sh $DEMUXLET_OUTDIR/assignments_refined.tsv.gz > $DEMUXLET_OUTDIR/demuxalot_summary.tsv
singularity exec Demuxafy.sif bash Demuxalot_summary.sh $DEMUXLET_OUTDIR/assignments.tsv.gz > $DEMUXLET_OUTDIR/demuxalot_summary.tsv

