#!/bin/bash
#$ -S /bin/bash
#$ -q short.q
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=8G
#$ -l tmp_requested=8G
#$ -pe smp 32
#$ -N demuxalot_demuxafy_TenK10K_scRNA
#$ -e /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/demuxalot/logs/demuxalot_TenK10K_scRNA_new_env_S0026a.err
#$ -o /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/demuxalot/logs/demuxalot_TenK10K_scRNA_new_env_S0026a.log
#$ -t 1-1
#$ -m ae
#$ -M a.cuomo@garvan.org.au

# SIF=/share/ScratchGeneral/anncuo/software/Demuxafy.sif
# BIND_PATH_DATA=/directflow
# BIND_PATH_OUTPUT=/share/ScratchGeneral/anncuo
PY_ENV=/directflow/SCCGGroupShare/projects/DrewNeavin/software/anaconda3/envs/demuxalot/bin/python
PY_SCRIPT=/directflow/SCCGGroupShare/projects/DrewNeavin/Demultiplex_Benchmark/Demultiplexing_Doublet_Detecting_Docs/scripts/Demuxalot.py

# i=${SGE_TASK_ID};
# SAMPLE=$(sed "${i}q;d" /share/ScratchGeneral/anncuo/tenk10k/data_processing/cellranger_outs.txt)

SAMPLE=S0026a

now=$(date)
echo "$now"

echo "Performing Demuxalot demultiplexing + doublet detection on sample: $SAMPLE"

VCF=/share/ScratchGeneral/anncuo/tenk10k/data_processing/genotypes/Merged_MAF0.01.dose_GeneFiltered_hg38_chr_NoAdditionalchr.vcf.gz
BARCODES=/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/${SAMPLE}/outs/filtered_feature_bc_matrix/barcodes.tsv.gz
BAM=/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/${SAMPLE}/outs/possorted_genome_bam.bam
DEMUXALOT_OUTDIR="/share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/demuxalot_output/${SAMPLE}"
INDS=/share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/donor_list.txt

mkdir /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/demuxalot_output/${SAMPLE}

$PY_ENV $PY_SCRIPT \
          -b $BARCODES \
          -a $BAM \
          -n $INDS \
          -v $VCF \
          -o $DEMUXALOT_OUTDIR \
          -r True
