#!/bin/bash
#$ -S /bin/bash
#$ -q short.q
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=80G
#$ -N dropulation_demuxafy_TenK10K_scRNA
#$ -e /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/dropulation/logs/dropulation_TenK10K_scRNA.err
#$ -o /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/dropulation/logs/dropulation_TenK10K_scRNA.log
#$ -t 1-64

SIF=/share/ScratchGeneral/anncuo/software/Demuxafy.sif
BIND_PATH_DATA=/directflow
BIND_PATH_OUTPUT=/share/ScratchGeneral/anncuo
​
i=${SGE_TASK_ID};

SAMPLE=$(sed "${i}q;d" /share/ScratchGeneral/anncuo/tenk10k/data_processing/cellranger_outs.txt)
​
echo "Performing dropulation demultiplexing + doublet detection on sample: $SAMPLE"
​
COUNTS="/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/$SAMPLE/outs/filtered_feature_bc_matrix.h5"
DROPULATION_OUTDIR="/share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/dropulation_output/${SAMPLE}"

# update the below
VCF=/path/to/TestData4PipelineFull/test_dataset.vcf
BARCODES=/path/to/TestData4PipelineFull/test_dataset/outs/filtered_gene_bc_matrices/Homo_sapiens_GRCh38p10/barcodes.tsv
BAM=/path/to/test_dataset/possorted_genome_bam.bam
DROPULATION_OUTDIR=/path/to/output/dropulation
INDS=/path/to/TestData4PipelineFull/donor_list.txt
GTF=/path/to/genes.gtf

mkdir /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/dropulation_output/${SAMPLE}
​
# Bam annotation
singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF TagReadWithGeneFunction \
                --ANNOTATIONS_FILE $GTF \
                --INPUT $BAM \
                --OUTPUT $DROPULATION_OUTDIR/possorted_genome_bam_dropulation_tag.bam


# Dropulation Assignment
singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF AssignCellsToSamples \
                --CELL_BC_FILE $BARCODES \
                --INPUT_BAM $DROPULATION_OUTDIR/possorted_genome_bam_dropulation_tag.bam \
                --OUTPUT $DROPULATION_OUTDIR/assignments.tsv.gz \
                --VCF $VCF \
                --SAMPLE_FILE $INDS \
                --CELL_BARCODE_TAG 'CB' \
                --MOLECULAR_BARCODE_TAG 'UB' \
                --VCF_OUTPUT $DROPULATION_OUTDIR/assignment.vcf \
                --MAX_ERROR_RATE 0.05


# Dropulation Doublet
singularity exec Demuxafy.sif DetectDoublets --CELL_BC_FILE $BARCODES \
          --INPUT_BAM $DROPULATION_OUTDIR/possorted_genome_bam_dropulation_tag.bam \
          --OUTPUT $DROPULATION_OUTDIR/likelihoods.tsv.gz \
          --VCF $VCF \
          --CELL_BARCODE_TAG 'CB' \
          --MOLECULAR_BARCODE_TAG 'UB' \
          --SINGLE_DONOR_LIKELIHOOD_FILE $DROPULATION_OUTDIR/assignments.tsv.gz \
          --SAMPLE_FILE $INDS \
          --MAX_ERROR_RATE 0.05


# Dropulation Call
singularity exec Demuxafy.sif dropulation_call.R --assign $DROPULATION_OUTDIR/assignments.tsv.gz \
                           --doublet $DROPULATION_OUTDIR/likelihoods.tsv.gz \
                           --out $DROPULATION_OUTDIR/updated_assignments.tsv.gz

# Dropulation Summary
singularity exec Demuxafy.sif bash Dropulation_summary.sh $DROPULATION_OUTDIR/updated_assignments.tsv.gz > $DROPULATION_OUTDIR/dropulation_summary.tsv
