#!/bin/bash
#$ -S /bin/bash
#$ -q short.q
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=10G
#$ -l tmp_requested=10G
#$ -N vireo_demuxafy_TenK10K_scRNA
#$ -e /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/vireo/logs/vireo_TenK10K_scRNA_rerun.err
#$ -o /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/vireo/logs/vireo_TenK10K_scRNA_rerun.log
#$ -t 1-12
#$ -m ae
#$ -M a.cuomo@garvan.org.au

SIF=/share/ScratchGeneral/anncuo/software/Demuxafy.sif
BIND_PATH_DATA=/directflow
BIND_PATH_OUTPUT=/share/ScratchGeneral/anncuo

#PARAMS="/share/ScratchGeneral/anncuo/tenk10k/data_processing/libraries_nsamples.txt"
PARAMS="/share/ScratchGeneral/anncuo/tenk10k/data_processing/libraries_nsamples_rerun.txt"

SAMPLE=`head -n $SGE_TASK_ID $PARAMS | tail -n 1 | awk '{print $1}'`
N_EXPECTED_DONORS=`head -n $SGE_TASK_ID $PARAMS | tail -n 1 | awk '{print $2}'`

now=$(date)
echo "$now"

echo "Performing vireo demultiplexing + doublet detection on sample: $SAMPLE, with $N_EXPECTED_DONORS expected donors"

BARCODES=/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/${SAMPLE}/outs/filtered_feature_bc_matrix/barcodes.tsv.gz
BAM=/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/${SAMPLE}/outs/possorted_genome_bam.bam
VIREO_OUTDIR="/share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/vireo_output/${SAMPLE}"
VCF=/share/ScratchGeneral/anncuo/tenk10k/data_processing/genotypes/Merged_MAF0.01.dose_GeneFiltered_hg38_chr_NoAdditionalchr.vcf.gz
INDS=/share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/samples_in_pools/${SAMPLE}.tsv
FIELD="GT" 

mkdir /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/vireo_output/${SAMPLE}

# Count number of alleles using cellSNP-lite
singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF cellsnp-lite \
                -s $BAM -b $BARCODES \
                -O $VIREO_OUTDIR \
                -R $VCF \
                -p 20 \
                --minMAF 0.1 \
                --minCOUNT 20 \
                --gzip

# Filter SNPs identified by cellSNP-lite
singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF bcftools view $VCF -R $VIREO_OUTDIR/cellSNP.base.vcf.gz -S $INDS -Ov -o $VIREO_OUTDIR/donor_subset.vcf

# Demultiplex using vireo
singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF vireo \
                -c $VIREO_OUTDIR \
                -d $VIREO_OUTDIR/donor_subset.vcf \
                -o $VIREO_OUTDIR \
                -t $FIELD \
                -N $N_EXPECTED_DONORS
