#!/bin/bash
#$ -S /bin/bash
#$ -q short.q
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=80G
#$ -N combiner_demuxafy_TenK10K_scRNA
#$ -e /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/demuxafy/combine_results/logs/comb_TenK10K_scRNA_vireo_S0045_S0046_240214_no_cb.err
#$ -o /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/demuxafy/combine_results/logs/comb_TenK10K_scRNA_vireo_S0045_S0046_240214_no_cb.log
#$ -t 1-16
#$ -m ae
#$ -M b.bowen@garvan.org.au

SIF=/share/ScratchGeneral/anncuo/software/Demuxafy.sif
BIND_PATH_DATA=/directflow
# BIND_PATH_OUTPUT=/share/ScratchGeneral/anncuo

i=${SGE_TASK_ID};

SAMPLE=$(sed "${i}q;d" /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/cellranger_outs_240214.txt)

echo "Combining all doublet detection results for sample: $SAMPLE"

OUTDIR="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/demuxafy/combine_results/output/combined_output_scds_scdblfinder_vireo_no_cb/$SAMPLE"
SCDS_OUTDIR="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/demuxafy/scds/output/$SAMPLE"
SCDBLFINDER_OUTDIR="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/demuxafy/scdblfinder/output/$SAMPLE"
VIREO_OUTDIR="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/demuxafy/vireo/output/$SAMPLE"

singularity exec --bind $BIND_PATH_DATA \
                $SIF Combine_Results.R \
                -o $OUTDIR/combined_results.tsv \
                --scds $SCDS_OUTDIR \
                --scDblFinder $SCDBLFINDER_OUTDIR \
                --vireo $VIREO_OUTDIR \
                --method "MajoritySinglet" ## there are other methods that can also be used, please see the help message above for the other options
