#!/bin/bash
#$ -S /bin/bash
#$ -q short.q
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=80G
#$ -N scdblfinder_demuxafy_TenK10K_scRNA
#$ -e /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/scdblfinder/logs/scdblfinder_TenK10K_scRNA_231214.err
#$ -o /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/scdblfinder/logs/scdblfinder_TenK10K_scRNA_231214.log
#$ -t 2-41
#$ -m ae
#$ -M a.cuomo@garvan.org.au

SIF=/share/ScratchGeneral/anncuo/software/Demuxafy.sif
BIND_PATH_DATA=/directflow
BIND_PATH_OUTPUT=/share/ScratchGeneral/anncuo

i=${SGE_TASK_ID};

SAMPLE=$(sed "${i}q;d" /share/ScratchGeneral/anncuo/tenk10k/data_processing/cellranger_outs_231214.txt)

echo "Performing scDblFinder doublet detection on sample: $SAMPLE"

#COUNTS="/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/$SAMPLE/outs/filtered_feature_bc_matrix.h5"
COUNTS="/directflow/GWCCGPipeline/projects/deliver/GIMR_GWCCG_230201_JOSPOW_10x_Tenk10k/231214_tenk10k_gencode44/cellranger_outs/$SAMPLE/cellranger_count/$SAMPLE/outs/filtered_feature_bc_matrix.h5"
SCDBLFINDER_OUTDIR="/share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/scdblfinder_output/${SAMPLE}"

mkdir /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/scdblfinder_output/${SAMPLE}

singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF scDblFinder.R \
                -t $COUNTS \
                -o $SCDBLFINDER_OUTDIR 
                
