#!/bin/bash
#$ -S /bin/bash
#$ -q short.q
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=80G
#$ -N dropulation_demuxafy_TenK10K_scRNA
#$ -e /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/dropulation/logs/dropulation_TenK10K_scRNA.err
#$ -o /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/dropulation/logs/dropulation_TenK10K_scRNA.log
#$ -t 1-1

SIF=/share/ScratchGeneral/anncuo/software/Demuxafy.sif
BIND_PATH_DATA=/directflow
BIND_PATH_OUTPUT=/share/

# i=${SGE_TASK_ID};
# SAMPLE=$(sed "${i}q;d" /share/ScratchGeneral/anncuo/tenk10k/data_processing/cellranger_outs.txt)

SAMPLE=S0016b

now=$(date)
echo "$now"

echo "Performing Dropulation demultiplexing + doublet detection on sample: $SAMPLE"

VCF=/share/ScratchGeneral/anncuo/tenk10k/data_processing/genotypes/Merged_MAF0.05_hg38_chr.vcf.gz
BARCODES=/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/${SAMPLE}/outs/filtered_feature_bc_matrix/barcodes.tsv.gz
BAM=/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/${SAMPLE}/outs/possorted_genome_bam.bam
DROPULATION_OUTDIR="/share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/dropulation_output/${SAMPLE}"
INDS=/share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/donor_list.txt
GTF=/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/gencode.v44.chr_patch_hapl_scaff.basic.annotation.gtf.gz

#mkdir /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/dropulation_output/${SAMPLE}

# Bam annotation
#singularity exec --bind $BIND_PATH_DATA \
#                --bind $BIND_PATH_OUTPUT \
#                $SIF TagReadWithGeneFunction \
#                --ANNOTATIONS_FILE $GTF \
#                --INPUT $BAM \
#                --OUTPUT $DROPULATION_OUTDIR/possorted_genome_bam_dropulation_tag.bam


# Dropulation Assignment
singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF AssignCellsToSamples \
                --CELL_BC_FILE $BARCODES \
                --INPUT_BAM $DROPULATION_OUTDIR/possorted_genome_bam_dropulation_tag.bam \
                --OUTPUT $DROPULATION_OUTDIR/assignments.tsv.gz \
                --VCF $VCF \
                --SAMPLE_FILE $INDS \
                --CELL_BARCODE_TAG 'CB' \
                --MOLECULAR_BARCODE_TAG 'UB' \
                --VCF_OUTPUT $DROPULATION_OUTDIR/assignment.vcf \
                --MAX_ERROR_RATE 0.05


# Dropulation Doublet
singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF DetectDoublets --CELL_BC_FILE $BARCODES \
                --INPUT_BAM $DROPULATION_OUTDIR/possorted_genome_bam_dropulation_tag.bam \
                --OUTPUT $DROPULATION_OUTDIR/likelihoods.tsv.gz \
                --VCF $VCF \
                --CELL_BARCODE_TAG 'CB' \
                --MOLECULAR_BARCODE_TAG 'UB' \
                --SINGLE_DONOR_LIKELIHOOD_FILE $DROPULATION_OUTDIR/assignments.tsv.gz \
                --SAMPLE_FILE $INDS \
                --MAX_ERROR_RATE 0.05


# Dropulation Call
singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF dropulation_call.R \
                --assign $DROPULATION_OUTDIR/assignments.tsv.gz \
                --doublet $DROPULATION_OUTDIR/likelihoods.tsv.gz \
                --out $DROPULATION_OUTDIR/updated_assignments.tsv.gz

# Dropulation Summary
singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF bash Dropulation_summary.sh $DROPULATION_OUTDIR/updated_assignments.tsv.gz > $DROPULATION_OUTDIR/dropulation_summary.tsv
