#!/bin/bash
#$ -S /bin/bash
#$ -q short.q
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=80G
#$ -N doublet_detection_demuxafy_TenK10K_scRNA
#$ -e /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/doublet_detection/logs/doublet_detection_TenK10K_scRNA.err
#$ -o /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/doublet_detection/logs/doublet_detection_TenK10K_scRNA.log
#$ -t 1-1

SIF=/share/ScratchGeneral/anncuo/software/Demuxafy.sif
BIND_PATH_DATA=/directflow
BIND_PATH_OUTPUT=/share/ScratchGeneral/anncuo
​
# i=${SGE_TASK_ID};
# SAMPLE=$(sed "${i}q;d" /share/ScratchGeneral/anncuo/tenk10k/data_processing/cellranger_outs.txt)

SAMPLE=S0016b

echo "Performing DoubletDetection doublet detection on sample: $SAMPLE"
​
COUNTS="/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/${SAMPLE}/outs/filtered_feature_bc_matrix.h5"
BARCODES="/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/${SAMPLE}/outs/filtered_feature_bc_matrix/barcodes.tsv.gz"
DOUBLETDETECTION_OUTDIR="/share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/doubletdetection_output/$SAMPLE"

mkdir /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/doubletdetection_output/$SAMPLE
​
singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF DoubletDetection.py \
                -m $COUNTS \
                -b $BARCODES \
                -o $DOUBLETDETECTION_OUTDIR 
                
