#!/bin/bash
#$ -S /bin/bash
#$ -q short.q
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=8G
#$ -l tmp_requested=8G
#$ -pe smp 32
#$ -N vireo_demuxafy_TenK10K_scRNA
#$ -e /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/vireo/logs/vireo_TenK10K_scRNA_S0018b.err
#$ -o /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy_output/vireo/logs/vireo_TenK10K_scRNA_S0018b.log
#$ -t 1-1
#$ -m ae
#$ -M a.cuomo@garvan.org.au

SIF=/share/ScratchGeneral/anncuo/software/Demuxafy.sif
BIND_PATH_DATA=/directflow
BIND_PATH_OUTPUT=/share/ScratchGeneral/anncuo

# i=${SGE_TASK_ID};
# SAMPLE=$(sed "${i}q;d" /share/ScratchGeneral/anncuo/tenk10k/data_processing/cellranger_outs.txt)

SAMPLE=S0026a

now=$(date)
echo "$now"

echo "Performing vireo demultiplexing + doublet detection on sample: $SAMPLE"

VCF=/share/ScratchGeneral/anncuo/tenk10k/data_processing/genotypes/Merged_MAF0.01.dose_GeneFiltered_hg38_chr_NoAdditionalchr.vcf.gz
BARCODES=/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/${SAMPLE}/outs/filtered_feature_bc_matrix/barcodes.tsv.gz
BAM=/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/${SAMPLE}/outs/possorted_genome_bam.bam
VIREO_OUTDIR="/share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/vireo_output/${SAMPLE}"
INDS=/share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/donor_list.txt

mkdir /share/ScratchGeneral/anncuo/tenk10k/data_processing/demuxafy/vireo_output/${SAMPLE}

singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF Demuxalot.py \
                -b $BARCODES \
                -a $BAM \
                -n $INDS \
                -v $VCF \
                -o $VIREO_OUTDIR \
                -r True


# Summarise results (with and without refinement)
singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF bash demuxalot_summary.sh $VIREO_OUTDIR/assignments_refined.tsv.gz > $VIREO_OUTDIR/demuxalot_summary_refined.tsv
singularity exec --bind $BIND_PATH_DATA \
                --bind $BIND_PATH_OUTPUT \
                $SIF bash demuxalot_summary.sh $VIREO_OUTDIR/assignments.tsv.gz > $VIREO_OUTDIR/demuxalot_summary.tsv

