#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=80G
#$ -l tmp_requested=50G
#$ -l nvgpu=3
#$ -N cellbender_TenK10K_scRNA
#$ -e /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/cellbender/logs/cellbender_TenK10K_scRNA_240214.err
#$ -o /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/cellbender/logs/cellbender_TenK10K_scRNA_240214.log
#$ -t 1-16
#$ -m ae
#$ -M b.bowen@garvan.org.au

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/share/ScratchGeneral/anncuo/jupyter/conda_notebooks/envs/cellbender/lib/

echo "----------------------------------------------------------------"
echo " Running CellBender on TenK10K_scRNA samples"
echo "----------------------------------------------------------------"

SEQ_DATE="240214" # Date the library was sequenced, corresponding to file names

i=${SGE_TASK_ID};

SAMPLE=$(sed "${i}q;d" /directflow/SCCGGroupShare/projects/${USER}/tenk10k_phase1/data_processing/cellranger_outs_${SEQ_DATE}.txt)

#SAMPLE=S0001a

echo "Performing ambient background removal on sample: $SAMPLE"

CELLBENDER_OUTDIR="/directflow/SCCGGroupShare/projects/${USER}/tenk10k_phase1/data_processing/cellbender/output/smaller_learning_rate/${SAMPLE}/"
mkdir -p ${CELLBENDER_OUTDIR}
cd ${CELLBENDER_OUTDIR}

# COUNTS="/directflow/SCCGGroupShare/projects/data/experimental_data/projects/TenK10K/GencodeV44/$SAMPLE/outs/raw_feature_bc_matrix.h5"
# COUNTS="/directflow/GWCCGPipeline/projects/deliver/GIMR_GWCCG_230201_JOSPOW_10x_Tenk10k/231213_tenk10k_gencode44/cellranger_outs/$SAMPLE/cellranger_count/$SAMPLE/outs/raw_feature_bc_matrix.h5"
# COUNTS="/directflow/GWCCGPipeline/projects/deliver/GIMR_GWCCG_230201_JOSPOW_10x_Tenk10k/231214_tenk10k_gencode44/cellranger_outs/$SAMPLE/cellranger_count/$SAMPLE/outs/raw_feature_bc_matrix.h5"
# COUNTS="/directflow/GWCCGPipeline/projects/deliver/GIMR_GWCCG_230201_JOSPOW_10x_Tenk10k/240108_tenk10k_gencode44/cellranger_outs/$SAMPLE/cellranger_count/$SAMPLE/outs/raw_feature_bc_matrix.h5"
# COUNTS="/directflow/GWCCGPipeline/projects/deliver/GIMR_GWCCG_230201_JOSPOW_10x_Tenk10k/240112_tenk10k_gencode44/cellranger_outs/$SAMPLE/cellranger_count/$SAMPLE/outs/raw_feature_bc_matrix.h5"
# COUNTS="/directflow/GWCCGPipeline/projects/deliver/GIMR_GWCCG_230201_JOSPOW_10x_Tenk10k/240115_tenk10k_gencode44/cellranger_outs/$SAMPLE/cellranger_count/$SAMPLE/outs/raw_feature_bc_matrix.h5"
# COUNTS="/directflow/GWCCGPipeline/projects/deliver/GIMR_GWCCG_230201_JOSPOW_10x_Tenk10k/240116_tenk10k_gencode44/cellranger_outs/$SAMPLE/cellranger_count/$SAMPLE/outs/raw_feature_bc_matrix.h5"
# COUNTS="/directflow/GWCCGPipeline/projects/deliver/GIMR_GWCCG_230201_JOSPOW_10x_Tenk10k/240119_tenk10k_gencode44/cellranger_outs/$SAMPLE/cellranger_count/$SAMPLE/outs/raw_feature_bc_matrix.h5"
COUNTS="/directflow/GWCCGPipeline/projects/deliver/GIMR_GWCCG_230201_JOSPOW_10x_Tenk10k/${SEQ_DATE}_tenk10k_gencode44/cellranger_outs/${SAMPLE}/cellranger_count/${SAMPLE}/outs/raw_feature_bc_matrix.h5"

# conda run -n cellbender 
. /home/${USER}/miniconda3/etc/profile.d/conda.sh
conda activate /share/ScratchGeneral/anncuo/jupyter/conda_notebooks/envs/cellbender

cellbender remove-background \
      --cuda \
      --input $COUNTS \
      --output ${CELLBENDER_OUTDIR}cellbender_output.h5 \
      --learning-rate 1e-6
