#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=50G
#$ -l tmp_requested=20G
#$ -N make_seurat_for_cell_classification
#$ -q short.q
#$ -o /share/ScratchGeneral/anncuo/tenk10k/data_processing/scpred/logs/make_seurat_TenK10K_scRNA_S0037a.err
#$ -e /share/ScratchGeneral/anncuo/tenk10k/data_processing/scpred/logs/make_seurat_TenK10K_scRNA_S0037a.log
#$ -t 64-64
#$ -m ae
#$ -M a.cuomo@garvan.org.au

R_PATH="/share/ScratchGeneral/anncuo/jupyter/conda_notebooks/envs/r_notebook/bin"
RSCRIPT="make_Seurat_object_one_sample.R"

# Do the main job
${R_PATH}/Rscript ${RSCRIPT} ${SGE_TASK_ID}
