#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=80G
#$ -l tmp_requested=50G
#$ -N classify_cells_hierarchical_scpred
#$ -q short.q
#$ -e /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/logs/scpred_TenK10K_scRNA_240119_newseurat.err
#$ -o /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/logs/scpred_TenK10K_scRNA_240119_newseurat.log
#$ -t 1-17
#$ -m ae
#$ -M a.cuomo@garvan.org.au

SIF=/share/ScratchGeneral/anncuo/tenk10k/data_processing/scpred/cell_classification.sif
BIND_PATH_DATA=/directflow
BIND_PATH_OUTPUT=/share/ScratchGeneral/anncuo

i=${SGE_TASK_ID};
SAMPLE=$(sed "${i}q;d" /share/ScratchGeneral/anncuo/tenk10k/data_processing/cellranger_outs_240119.txt)

echo "Performing hierarchical scPred cell classification on sample: $SAMPLE"

RDS="/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/seurat_objects_unfiltered/${SAMPLE}.rds"
SCPRED_OUTDIR="/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/${SAMPLE}/step3_hierscpred/"

# mkdir /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/${SAMPLE}
# mkdir /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/${SAMPLE}/step3_hierscpred

cd $SGE_O_WORKDIR

# Run main command
singularity exec --bind $BIND_PATH_DATA \
                 --bind $BIND_PATH_OUTPUT \
                 -B $SGE_O_WORKDIR $SIF Rscript /map_hierscpred.R \
                 --file $RDS \
                 --path $SCPRED_OUTDIR \
                 --plan multiprocess



