#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=50G
#$ -l tmp_requested=20G
#$ -N make_seurat_for_cell_classification
#$ -q short.q
#$ -e /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scpred/logs/make_seurat_TenK10K_scRNA_240214.err
#$ -o /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scpred/logs/make_seurat_TenK10K_scRNA_240214.log
#$ -t 1-16
#$ -m ae
#$ -M b.bowen@garvan.org.au

R_PATH="/share/ScratchGeneral/anncuo/jupyter/conda_notebooks/envs/r_notebook/bin"
RSCRIPT="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/Celltyping/scpred/make_Seurat_object_one_sample.R"

# Do the main job
${R_PATH}/Rscript ${RSCRIPT} ${SGE_TASK_ID}
