#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=80G
#$ -l tmp_requested=40G
#$ -N make_seurat_for_cell_classification
#$ -q short.q
#$ -e /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scpred/logs/make_seurat_TenK10K_scRNA_240223.err
#$ -o /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scpred/logs/make_seurat_TenK10K_scRNA_240223.log
#$ -t 2-2
#$ -m ae
#$ -M b.bowen@garvan.org.au

R_PATH="/share/ScratchGeneral/anncuo/jupyter/conda_notebooks/envs/r_notebook/bin"
RSCRIPT="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/Celltyping/scpred/make_Seurat_object_one_sample.R"
SEQ_DATE=240223

# make separate logs for each sample so it's easier to see what's going on 
SAMPLE=$(sed "${SGE_TASK_ID}q;d" /directflow/SCCGGroupShare/projects/${USER}/tenk10k_phase1/data_processing/cellranger_outs_${SEQ_DATE}.txt)
LOG="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scpred/logs/sample_logs/make_seurat_${SAMPLE}_task${SGE_TASK_ID}.log"

# Do the main job
${R_PATH}/Rscript ${RSCRIPT} ${SGE_TASK_ID} ${SEQ_DATE} &>> ${LOG}
