#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=100G
#$ -l tmp_requested=80G
#$ -N hierscpred_classify_cells
#$ -q short.q
#$ -e /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scpred/logs/hierscpred_TenK10K_scRNA_240524_newseurat.err
#$ -o /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scpred/logs/hierscpred_TenK10K_scRNA_240524_newseurat.log
#$ -t 1-27
#$ -m ae
#$ -M b.bowen@garvan.org.au

SIF=/share/ScratchGeneral/anncuo/tenk10k/data_processing/scpred/cell_classification.sif
BIND_PATH_DATA=/directflow
#BIND_PATH_OUTPUT=/share/ScratchGeneral/anncuo

# Date the library was sequenced, corresponding to file names

# SEQ_DATE="240223"
# SEQ_DATE="240501"
SEQ_DATE="240524"

i=${SGE_TASK_ID};
SAMPLE=$(sed "${i}q;d" /directflow/SCCGGroupShare/projects/${USER}/tenk10k_phase1/data_processing/cellranger_outs_${SEQ_DATE}.txt)

echo "Performing hierarchical scPred cell classification on sample: ${SAMPLE}"

RDS="/directflow/SCCGGroupShare/projects/${USER}/tenk10k_phase1/data_processing/scpred/seurat_objects_unfiltered/${SAMPLE}.rds"
SCPRED_OUTDIR="/directflow/SCCGGroupShare/projects/${USER}/tenk10k_phase1/data_processing/scpred/${SAMPLE}/step3_hierscpred/"

mkdir -p ${SCPRED_OUTDIR}

# mkdir /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/${SAMPLE}
# mkdir /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/${SAMPLE}/step3_hierscpred
LOG="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scpred/logs/sample_logs/hierscpred_${SAMPLE}_task${SGE_TASK_ID}.log"

cd $SGE_O_WORKDIR

# Run main command
singularity exec --bind $BIND_PATH_DATA \
                 -B $SGE_O_WORKDIR $SIF Rscript /map_hierscpred.R \
                 --file $RDS \
                 --path $SCPRED_OUTDIR \
                 --plan multiprocess &>> ${LOG}
