#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=100G
#$ -l tmp_requested=80G
#$ -N classify_cells_azimuth
#$ -q short.q
#$ -e /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/logs/azimuth_TenK10K_scRNA_231013_newseurat.err
#$ -o /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/logs/azimuth_TenK10K_scRNA_231013_newseurat.log
#$ -t 1-64
#$ -m ae
#$ -M a.cuomo@garvan.org.au

SIF=/share/ScratchGeneral/anncuo/tenk10k/data_processing/scpred/cell_classification.sif
BIND_PATH_DATA=/directflow
BIND_PATH_OUTPUT=/share/ScratchGeneral/anncuo

i=${SGE_TASK_ID};
SAMPLE=$(sed "${i}q;d" /share/ScratchGeneral/anncuo/tenk10k/data_processing/cellranger_outs_231013.txt)

echo "Performing Azimuth cell classification on sample: $SAMPLE"

RDS="/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/seurat_objects_unfiltered/${SAMPLE}.rds"
AZIMUTH_OUTDIR="/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/${SAMPLE}/step2_azimuth/"

# mkdir /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/${SAMPLE}
# mkdir /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scpred/${SAMPLE}/step2_azimuth

cd $SGE_O_WORKDIR

# Run main command
singularity exec --bind $BIND_PATH_DATA \
                 --bind $BIND_PATH_OUTPUT \
                 -B $SGE_O_WORKDIR $SIF Rscript /map_azimuth.R \
                 --file $RDS \
                 --path $AZIMUTH_OUTDIR 


