#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=50G
#$ -l tmp_requested=20G
#$ -N run_celltypist_per_sample
#$ -q short.q
#$ -e /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/celltypist/logs/run_celltypist_TenK10K_scRNA_240524.err
#$ -o /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/celltypist/logs/run_celltypist_TenK10K_scRNA_240524.log
#$ -t 1-27
#$ -m ae
#$ -M b.bowen@garvan.org.au

PY_PATH="/share/ScratchGeneral/anncuo/jupyter/conda_notebooks/envs/cellregmap_notebook/bin/"
PYSCRIPT="/directflow/SCCGGroupShare/projects/${USER}/tenk10k_phase1/Celltyping/celltypist/celltypist_per_sample.py"
SEQ_DATE=240524

# Do the main job
${PY_PATH}/python ${PYSCRIPT} ${SGE_TASK_ID} ${SEQ_DATE}
