#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=80G
#$ -l tmp_requested=40G
#$ -N prepare_ct_covs
#$ -q short.q
#$ -e /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scanpy/logs/prepare_ct_covs.err
#$ -o /directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/data_processing/scanpy/logs/prepare_ct_covs.log
#$ -t 1-28
#$ -m ae
#$ -M a.cuomo@garvan.org.au

PY_PATH="/share/ScratchGeneral/anncuo/jupyter/conda_notebooks/envs/cellregmap_notebook/bin/"
PYSCRIPT="/share/ScratchGeneral/anncuo/github_repos/tenk10k_phase1/Scanpy/prepare_cell_covs.py"

i=${SGE_TASK_ID};
CELLTYPE=$(sed "${i}q;d" /share/ScratchGeneral/anncuo/tenk10k/data_processing/scanpy/celltypes.txt)

# Do the main job
${PY_PATH}/python ${PYSCRIPT} ${CELLTYPE} 
