#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=500G
#$ -l tmp_requested=40G
#$ -N prepare_ct_covs
#$ -q long.q
#$ -e /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scanpy/logs/prepare_ct_covs.err
#$ -o /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scanpy/logs/prepare_ct_covs.log
#$ -t 1-28
#$ -m ae
#$ -M b.bowen@garvan.org.au

# NOTE: some of the cell types require more memory than others

PY_PATH="/directflow/SCCGGroupShare/projects/blabow/.conda/envs/cellregmap_notebook_bb/bin"
PYSCRIPT="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/Scanpy/prepare_cell_covs.py"

i=${SGE_TASK_ID};
CELLTYPE=$(sed "${i}q;d" /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scanpy/output/integrated_objects/unique_cell_types_wg2_scpred.txt)
LOG="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scanpy/logs/cell_type_logs/${CELLTYPE}_prepare_ct_covs_task${SGE_TASK_ID}.log"

# Do the main job
${PY_PATH}/python ${PYSCRIPT} ${CELLTYPE} &>> ${LOG}
