#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=20G
#$ -l tmp_requested=10G
#$ -N run_celltypist_per_sample
#$ -q short.q
#$ -e /share/ScratchGeneral/anncuo/tenk10k/data_processing/scpred/logs/run_celltypist_TenK10K_scRNA_231213.err
#$ -o /share/ScratchGeneral/anncuo/tenk10k/data_processing/scpred/logs/run_celltypist_TenK10K_scRNA_231213.log
#$ -t 2-24
#$ -m ae
#$ -M a.cuomo@garvan.org.au

PY_PATH="/share/ScratchGeneral/anncuo/jupyter/conda_notebooks/envs/cellregmap_notebook/bin/"
PYSCRIPT="/share/ScratchGeneral/anncuo/github_repos/tenk10k_phase1/Scanpy/celltypist_per_sample.py"

# Do the main job
${PY_PATH}/python ${PYSCRIPT} ${SGE_TASK_ID}
