#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=80G
#$ -l tmp_requested=40G
#$ -N add_metadata_per_sample
#$ -q short.q
#$ -e /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scanpy/logs/add_metadata_TenK10K_scRNA_all_batches.err
#$ -o /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scanpy/logs/add_metadata_TenK10K_scRNA_all_batches.log
#$ -t 1-257
#$ -m ae
#$ -M b.bowen@garvan.org.au

PY_PATH="/share/ScratchGeneral/anncuo/jupyter/conda_notebooks/envs/cellregmap_notebook/bin/"
PYSCRIPT="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/Scanpy/add_metadata_per_sample_no_norm.py"

# Do the main job
${PY_PATH}/python ${PYSCRIPT} ${SGE_TASK_ID}
