#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -r yes
#$ -l mem_requested=1000G
#$ -l tmp_requested=40G
#$ -N harmony_umap
#$ -q long.q
#$ -e /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scanpy/logs/umap_all_batches.err
#$ -o /directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/data_processing/scanpy/logs/umap_all_batches.log
#$ -m ae
#$ -M b.bowen@garvan.org.au

PY_PATH="/directflow/SCCGGroupShare/projects/blabow/.conda/envs/cellregmap_notebook_bb/bin"

# first pass harmony + UMAP
# PYSCRIPT="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/Scanpy/harmony_umap.py"

# second pass harmony + UMAP (after manual filtering of low-quality clusters)
# PYSCRIPT="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/Scanpy/rerun_harmony_umap.py"

# umap npcs testing / umap n hvgs testing 
PYSCRIPT="/directflow/SCCGGroupShare/projects/blabow/tenk10k_phase1/Scanpy/run_umap_different_pcs.py"

cd ${TMPDIR}
# Run python script
echo "${PY_PATH}/python ${PYSCRIPT}"

${PY_PATH}/python ${PYSCRIPT}